/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2206 from the
 * contents of LibVorbis.xs. Do not edit this file, edit LibVorbis.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "LibVorbis.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <errno.h>
#include <stdlib.h>

#include <ogg/ogg.h>
#include <vorbis/codec.h>
#include <vorbis/vorbisenc.h>
#include <vorbis/vorbisfile.h>

#include "const-c.inc"

static size_t ovcb_read(void *ptr, size_t size, size_t nmemb, void *datasource);
static int    ovcb_seek(void *datasource, ogg_int64_t offset, int whence);
static int    ovcb_close(void *datasource);
static long   ovcb_tell(void *datasource);

/* http://www.xiph.org/ogg/vorbis/doc/vorbisfile/ov_callbacks.html */
ov_callbacks vorbis_callbacks = {
	ovcb_read,
	ovcb_seek,
	ovcb_close,
	ovcb_tell
};

/* Allow multiple instances of the decoder object. Stuff each filehandle into (void*)stream */
typedef struct {
	int is_streaming;
	int bytes_streamed;
	int last_bitstream;
	PerlIO *stream;

} ocvb_datasource;

typedef PerlIO *        OutputStream;
typedef PerlIO *        InputStream;

/* useful items from XMMS */
static size_t ovcb_read(void *ptr, size_t size, size_t nmemb, void *vdatasource) {

  size_t read_bytes = 0;
  ocvb_datasource *datasource = vdatasource;

  read_bytes = PerlIO_read(datasource->stream, ptr, size * nmemb);
  datasource->bytes_streamed += read_bytes;

  return read_bytes;
}

static int ovcb_seek(void *vdatasource, ogg_int64_t offset, int whence) {

  ocvb_datasource *datasource = vdatasource;

  if (datasource->is_streaming) {
    return -1;
  }

  /* For some reason PerlIO_seek fails miserably here. < 5.8.1 works */
  /* return PerlIO_seek(datasource->stream, offset, whence); */

  return fseek(PerlIO_findFILE(datasource->stream), offset, whence);
}

static int ovcb_close(void *vdatasource) {

  ocvb_datasource *datasource = vdatasource;

  return PerlIO_close(datasource->stream);
}

static long ovcb_tell(void *vdatasource) {

  ocvb_datasource *datasource = vdatasource;

  if (datasource->is_streaming) {
    return datasource->bytes_streamed;
  }

  return PerlIO_tell(datasource->stream);
}


#line 100 "LibVorbis.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 152 "LibVorbis.c"

/* INCLUDE:  Including 'const-xs.inc' from 'LibVorbis.xs' */


XS(XS_Ogg__Vorbis__LibVorbis_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_constant)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "./const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	IV		iv;
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 181 "LibVorbis.c"
	SV *	sv = ST(0);
	const char *	s = SvPV(sv, len);
#line 18 "./const-xs.inc"
        /* Change this to constant(aTHX_ s, len, &iv, &nv);
           if you need to return both NVs and IVs */
	type = constant(aTHX_ s, len, &iv);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid Ogg::Vorbis::LibVorbis macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined Ogg::Vorbis::LibVorbis macro %s, used",
				   s));
          PUSHs(sv);
          break;
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break;
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing Ogg::Vorbis::LibVorbis macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 258 "LibVorbis.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'LibVorbis.xs' from 'const-xs.inc' */


XS(XS_Ogg__Vorbis__LibVorbis_make_oggvorbis_file); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_make_oggvorbis_file)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 116 "LibVorbis.xs"
    OggVorbis_File *memory;
#line 281 "LibVorbis.c"
	OggVorbis_File *	RETVAL;
	dXSTARG;
#line 118 "LibVorbis.xs"
    New(0, memory, 1, OggVorbis_File);
    RETVAL = memory;
#line 287 "LibVorbis.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_make_vorbis_info); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_make_vorbis_info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 139 "LibVorbis.xs"
    vorbis_info *	memory;
#line 307 "LibVorbis.c"
	vorbis_info *	RETVAL;
	dXSTARG;
#line 141 "LibVorbis.xs"
    New(0, memory, 1, vorbis_info);
    RETVAL = memory;
#line 313 "LibVorbis.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_open); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_open)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "f, vf, initial, ibytes");
    {
	InputStream	f = IoIFP(sv_2io(ST(0)));
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(1)));
	char *	initial = (char *)SvPV_nolen(ST(2));
	int	ibytes = (int)SvIV(ST(3));
#line 184 "LibVorbis.xs"
    FILE *fp = PerlIO_findFILE(f);
#line 337 "LibVorbis.c"
	int	RETVAL;
	dXSTARG;
#line 186 "LibVorbis.xs"
    /* check whether it is a valid file handler */
    if (fp == (FILE*) 0 || fileno(fp) <= 0) {   
      Perl_croak(aTHX_ "Expected Open FILE HANDLER");
    }
    /* open the vorbis file */
    RETVAL = ov_open(fp, vf, initial, ibytes);
#line 347 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_fopen); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_fopen)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "path, vf");
    {
	char *	path = (char *)SvPV_nolen(ST(0));
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(1)));
	int	RETVAL;
	dXSTARG;
#line 221 "LibVorbis.xs"
    RETVAL = ov_fopen(path, vf);
#line 371 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_open_callbacks); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_open_callbacks)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "path, vf, initial, ibytes");
    {
	SV *	path = ST(0);
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(1)));
	char *	initial = (char *)SvPV_nolen(ST(2));
	int	ibytes = (int)SvIV(ST(3));
#line 262 "LibVorbis.xs"
    FILE *fp;
#line 395 "LibVorbis.c"
	int	RETVAL;
	dXSTARG;
#line 264 "LibVorbis.xs"
    int ret = 10;

    /* our stash for streams */
    ocvb_datasource *datasource = (ocvb_datasource *) safemalloc(sizeof(ocvb_datasource));
    memset(datasource, 0, sizeof(ocvb_datasource));

    /* check and see if a pathname was passed in, otherwise it might be a
     * IO::Socket subclass, or even a *FH Glob */
    if (SvOK(path) && (SvTYPE(SvRV(path)) != SVt_PVGV)) {

      if ((datasource->stream = PerlIO_open((char*)SvPV_nolen(path), "r")) == NULL) {
        safefree(vf);
        printf("failed on open: [%d] - [%s]\n", errno, strerror(errno));
        XSRETURN_UNDEF;
      }

      datasource->is_streaming = 0;

    } else if (SvOK(path)) {

      /* Did we get a Glob, or a IO::Socket subclass? */		
      if (sv_isobject(path) && sv_derived_from(path, "IO::Socket")) {
        datasource->is_streaming = 1;
      } else {

        datasource->is_streaming = 0;
      }

      /* dereference and get the SV* that contains the Magic & FH,
       * then pull the fd from the PerlIO object */
      datasource->stream = IoIFP(GvIOp(SvRV(path)));

    } else {

      fp = PerlIO_findFILE((PerlIO *)IoIFP(sv_2io(path)));
      /* check whether it is a valid file handler */
      if (fp == (FILE*) 0 || fileno(fp) <= 0) {   
         XSRETURN_UNDEF;
      }
      datasource->stream = (PerlIO *)IoIFP(sv_2io(path));
    }

    if ((ret = ov_open_callbacks((void*)datasource, vf, NULL, 0, vorbis_callbacks)) < 0) {
      warn("Failed on registering callbacks: [%d]\n", ret);
      printf("failed on open: [%d] - [%s]\n", errno, strerror(errno));
      ov_clear(vf);

      XSRETURN_UNDEF;
    }

    datasource->bytes_streamed = 0;
    datasource->last_bitstream = -1;

    RETVAL = ret;

#line 454 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_test); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_test)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "f, vf, initial, ibytes");
    {
	InputStream	f = IoIFP(sv_2io(ST(0)));
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(1)));
	char *	initial = (char *)SvPV_nolen(ST(2));
	long	ibytes = (long)SvIV(ST(3));
#line 353 "LibVorbis.xs"
    FILE *fp = PerlIO_findFILE(f);
#line 478 "LibVorbis.c"
	int	RETVAL;
	dXSTARG;
#line 355 "LibVorbis.xs"
    if (fp == (FILE*) 0 || fileno(fp) <= 0) {   
       XSRETURN_UNDEF;
    }    
    /* open the vorbis file */
    RETVAL = ov_test(fp, vf, initial, ibytes);
#line 487 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_test_open); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_test_open)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	RETVAL;
	dXSTARG;
#line 388 "LibVorbis.xs"
    RETVAL = ov_test_open(vf);
#line 510 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_test_callbacks); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_test_callbacks)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "path, vf, initial, ibytes");
    {
	SV *	path = ST(0);
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(1)));
	char *	initial = (char *)SvPV_nolen(ST(2));
	int	ibytes = (int)SvIV(ST(3));
#line 429 "LibVorbis.xs"
    FILE *fp;
#line 534 "LibVorbis.c"
	int	RETVAL;
	dXSTARG;
#line 431 "LibVorbis.xs"
    int ret = 10;

    /* our stash for streams */
    ocvb_datasource *datasource = (ocvb_datasource *) safemalloc(sizeof(ocvb_datasource));
    memset(datasource, 0, sizeof(ocvb_datasource));

    /* check and see if a pathname was passed in, otherwise it might be a
     * IO::Socket subclass, or even a *FH Glob */
    if (SvOK(path) && (SvTYPE(SvRV(path)) != SVt_PVGV)) {

      if ((datasource->stream = PerlIO_open((char*)SvPV_nolen(path), "r")) == NULL) {
        safefree(vf);
        printf("failed on open: [%d] - [%s]\n", errno, strerror(errno));
        XSRETURN_UNDEF;
      }

      datasource->is_streaming = 0;

    } else if (SvOK(path)) {

      /* Did we get a Glob, or a IO::Socket subclass? */		
      if (sv_isobject(path) && sv_derived_from(path, "IO::Socket")) {
        datasource->is_streaming = 1;
      } else {

        datasource->is_streaming = 0;
      }

      /* dereference and get the SV* that contains the Magic & FH,
       * then pull the fd from the PerlIO object */
      datasource->stream = IoIFP(GvIOp(SvRV(path)));

    } else {

      fp = PerlIO_findFILE((PerlIO *)IoIFP(sv_2io(path)));
      /* check whether it is a valid file handler */
      if (fp == (FILE*) 0 || fileno(fp) <= 0) {   
         XSRETURN_UNDEF;
      }
      datasource->stream = (PerlIO *)IoIFP(sv_2io(path));
    }

    if ((ret = ov_test_callbacks((void*)datasource, vf, NULL, 0, vorbis_callbacks)) < 0) {
      warn("Failed on registering callbacks: [%d]\n", ret);
      printf("failed on open: [%d] - [%s]\n", errno, strerror(errno));
      ov_clear(vf);

      XSRETURN_UNDEF;
    }

    datasource->bytes_streamed = 0;
    datasource->last_bitstream = -1;

    RETVAL = ret;

#line 593 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_clear); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_clear)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	RETVAL;
	dXSTARG;
#line 508 "LibVorbis.xs"
    RETVAL = ov_clear(vf);
#line 616 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_seekable); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_seekable)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	RETVAL;
	dXSTARG;
#line 531 "LibVorbis.xs"
    RETVAL = ov_seekable(vf);
#line 639 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_time_total); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_time_total)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, i");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	i = (int)SvIV(ST(1));
	double	RETVAL;
	dXSTARG;
#line 557 "LibVorbis.xs"
    RETVAL = ov_time_total(vf, i);
#line 663 "LibVorbis.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, s");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	double	s = (double)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 588 "LibVorbis.xs"
    RETVAL = ov_time_seek(vf, s);
#line 687 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_seek); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_seek)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, s");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	long	s = (long)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 619 "LibVorbis.xs"
    RETVAL = ov_raw_seek(vf, s);
#line 711 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, s");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	ogg_int64_t	s = (ogg_int64_t)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 650 "LibVorbis.xs"
    RETVAL = ov_pcm_seek(vf, s);
#line 735 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_page); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_page)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, pos");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	ogg_int64_t	pos = (ogg_int64_t)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 681 "LibVorbis.xs"
    RETVAL = ov_pcm_seek_page(vf, pos);
#line 759 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek_page); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek_page)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, pos");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	double	pos = (double)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 712 "LibVorbis.xs"
    RETVAL = ov_time_seek_page(vf, pos);
#line 783 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_seek_lap); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_seek_lap)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, pos");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	ogg_int64_t	pos = (ogg_int64_t)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 744 "LibVorbis.xs"
    RETVAL = ov_raw_seek_lap(vf, pos);
#line 807 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_lap); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_lap)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, pos");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	long	pos = (long)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 776 "LibVorbis.xs"
    RETVAL = ov_pcm_seek_lap(vf, pos);
#line 831 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek_lap); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek_lap)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, pos");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	double	pos = (double)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 808 "LibVorbis.xs"
    RETVAL = ov_time_seek_lap(vf, pos);
#line 855 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek_page_lap); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek_page_lap)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, pos");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	double	pos = (double)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 840 "LibVorbis.xs"
    RETVAL = ov_time_seek_page_lap(vf, pos);
#line 879 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_page_lap); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_page_lap)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, pos");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	ogg_int64_t	pos = (ogg_int64_t)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 872 "LibVorbis.xs"
    RETVAL = ov_pcm_seek_page_lap(vf, pos);
#line 903 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_streams); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_streams)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	long	RETVAL;
	dXSTARG;
#line 895 "LibVorbis.xs"
    RETVAL = ov_streams(vf);
#line 926 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_info); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, link");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	link = (int)SvIV(ST(1));
	vorbis_info *	RETVAL;
	dXSTARG;
#line 920 "LibVorbis.xs"
    RETVAL = ov_info(vf, link);
#line 950 "LibVorbis.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_bitrate); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_bitrate)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, i");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	i = (int)SvIV(ST(1));
	long	RETVAL;
	dXSTARG;
#line 945 "LibVorbis.xs"
    RETVAL = ov_bitrate(vf, i);
#line 974 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_bitrate_instant); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_bitrate_instant)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	long	RETVAL;
	dXSTARG;
#line 969 "LibVorbis.xs"
    RETVAL = ov_bitrate_instant(vf);
#line 997 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_serialnumber); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_serialnumber)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, i");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	i = (int)SvIV(ST(1));
	long	RETVAL;
	dXSTARG;
#line 994 "LibVorbis.xs"
    RETVAL = ov_serialnumber(vf, i);
#line 1021 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_total); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_total)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, i");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	i = (int)SvIV(ST(1));
	long	RETVAL;
	dXSTARG;
#line 1020 "LibVorbis.xs"
    RETVAL = ov_raw_total(vf, i);
#line 1045 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_total); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_total)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, i");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	i = (int)SvIV(ST(1));
	ogg_int64_t	RETVAL;
	dXSTARG;
#line 1045 "LibVorbis.xs"
    RETVAL = ov_pcm_total(vf, i);
#line 1069 "LibVorbis.c"
	XSprePUSH; PUSHn((NV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_tell); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_tell)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	ogg_int64_t	RETVAL;
	dXSTARG;
#line 1068 "LibVorbis.xs"
    RETVAL = ov_raw_tell(vf);
#line 1092 "LibVorbis.c"
	XSprePUSH; PUSHn((NV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_tell); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_tell)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	ogg_int64_t	RETVAL;
	dXSTARG;
#line 1091 "LibVorbis.xs"
    RETVAL = ov_pcm_tell(vf);
#line 1115 "LibVorbis.c"
	XSprePUSH; PUSHn((NV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_time_tell); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_time_tell)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	ogg_int64_t	RETVAL;
	dXSTARG;
#line 1114 "LibVorbis.xs"
    RETVAL = ov_time_tell(vf);
#line 1138 "LibVorbis.c"
	XSprePUSH; PUSHn((NV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_comment); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_comment)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, link");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	link = (int)SvIV(ST(1));
	vorbis_comment *	RETVAL;
	dXSTARG;
#line 1139 "LibVorbis.xs"
    RETVAL = ov_comment(vf, link);
#line 1162 "LibVorbis.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_get_vorbis_info); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_get_vorbis_info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vi");
    {
	vorbis_info *	vi = INT2PTR(vorbis_info *,SvIV(ST(0)));
#line 1168 "LibVorbis.xs"
    HV * hash;
#line 1183 "LibVorbis.c"
	HV *	RETVAL;
#line 1170 "LibVorbis.xs"
    hash = newHV();

    sv_2mortal((SV *)hash);	/* convert the HASH to a mortal */
    hv_store(hash, "version", strlen("version"), newSVnv(vi->version), 0); 
    hv_store(hash, "channels", strlen("channels"), newSViv(vi->channels), 0); 
    hv_store(hash, "rate", strlen("rate"), newSVnv(vi->rate), 0);
    hv_store(hash, "bitrate_upper", strlen("bitrate_upper"), newSVnv(vi->bitrate_upper), 0);
    hv_store(hash, "bitrate_nominal", strlen("bitrate_nominal"), newSVnv(vi->bitrate_nominal), 0);
    hv_store(hash, "bitrate_lower", strlen("bitrate_lower"), newSVnv(vi->bitrate_lower), 0);
    hv_store(hash, "bitrate_window", strlen("bitrate_window"), newSVnv(vi->bitrate_window), 0);
    hv_store(hash, "codec_setup", strlen("codec_setup"), newSViv(PTR2IV(vi->codec_setup)), 0);

    RETVAL = hash;
#line 1199 "LibVorbis.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_get_vorbis_comment); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_get_vorbis_comment)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vc");
    {
	vorbis_comment *	vc = INT2PTR(vorbis_comment *,SvIV(ST(0)));
#line 1204 "LibVorbis.xs"
    HV * hash;
    AV * uc;			/* user comments */
    AV * cl;			/* comment lenth */
    int i = 0;
#line 1224 "LibVorbis.c"
	HV *	RETVAL;
#line 1209 "LibVorbis.xs"
    hash = newHV();
    sv_2mortal((SV *)hash);

    uc = newAV();
    cl = newAV();
    /* get the user comments and put in hash */
    for (i=0; i<vc->comments; i++) {
      av_push(uc, newSVpv(vc->user_comments[i], 0));
      av_push(cl, newSViv(vc->comment_lengths[i]));
    } 

    /* store the user comments */
    hv_store(hash, "user_comments", strlen("user_comments"), newRV_noinc((SV *)uc), 0);      
    /* store the comment length */
    hv_store(hash, "comment_lenghts", strlen("comment_lenghts"), newRV_noinc((SV *)cl), 0);      
    /* get the vendor */
    hv_store(hash, "vendor", strlen("vendor"), newSVpv(vc->vendor, 0), 0);      
    /* number of comments */
    hv_store(hash, "comments", strlen("comments"), newSViv(vc->comments), 0);      

    RETVAL = hash;

#line 1249 "LibVorbis.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ogg__Vorbis__LibVorbis); /* prototype to pass -Wmissing-prototypes */
XS(boot_Ogg__Vorbis__LibVorbis)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Ogg::Vorbis::LibVorbis::constant", XS_Ogg__Vorbis__LibVorbis_constant, file);
        newXS("Ogg::Vorbis::LibVorbis::make_oggvorbis_file", XS_Ogg__Vorbis__LibVorbis_make_oggvorbis_file, file);
        newXS("Ogg::Vorbis::LibVorbis::make_vorbis_info", XS_Ogg__Vorbis__LibVorbis_make_vorbis_info, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_open", XS_Ogg__Vorbis__LibVorbis_ov_open, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_fopen", XS_Ogg__Vorbis__LibVorbis_ov_fopen, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_open_callbacks", XS_Ogg__Vorbis__LibVorbis_ov_open_callbacks, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_test", XS_Ogg__Vorbis__LibVorbis_ov_test, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_test_open", XS_Ogg__Vorbis__LibVorbis_ov_test_open, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_test_callbacks", XS_Ogg__Vorbis__LibVorbis_ov_test_callbacks, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_clear", XS_Ogg__Vorbis__LibVorbis_ov_clear, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_seekable", XS_Ogg__Vorbis__LibVorbis_ov_seekable, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_time_total", XS_Ogg__Vorbis__LibVorbis_ov_time_total, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_time_seek", XS_Ogg__Vorbis__LibVorbis_ov_time_seek, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_raw_seek", XS_Ogg__Vorbis__LibVorbis_ov_raw_seek, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_pcm_seek", XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_pcm_seek_page", XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_page, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_time_seek_page", XS_Ogg__Vorbis__LibVorbis_ov_time_seek_page, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_raw_seek_lap", XS_Ogg__Vorbis__LibVorbis_ov_raw_seek_lap, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_pcm_seek_lap", XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_lap, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_time_seek_lap", XS_Ogg__Vorbis__LibVorbis_ov_time_seek_lap, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_time_seek_page_lap", XS_Ogg__Vorbis__LibVorbis_ov_time_seek_page_lap, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_pcm_seek_page_lap", XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_page_lap, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_streams", XS_Ogg__Vorbis__LibVorbis_ov_streams, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_info", XS_Ogg__Vorbis__LibVorbis_ov_info, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_bitrate", XS_Ogg__Vorbis__LibVorbis_ov_bitrate, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_bitrate_instant", XS_Ogg__Vorbis__LibVorbis_ov_bitrate_instant, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_serialnumber", XS_Ogg__Vorbis__LibVorbis_ov_serialnumber, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_raw_total", XS_Ogg__Vorbis__LibVorbis_ov_raw_total, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_pcm_total", XS_Ogg__Vorbis__LibVorbis_ov_pcm_total, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_raw_tell", XS_Ogg__Vorbis__LibVorbis_ov_raw_tell, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_pcm_tell", XS_Ogg__Vorbis__LibVorbis_ov_pcm_tell, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_time_tell", XS_Ogg__Vorbis__LibVorbis_ov_time_tell, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_comment", XS_Ogg__Vorbis__LibVorbis_ov_comment, file);
        newXS("Ogg::Vorbis::LibVorbis::get_vorbis_info", XS_Ogg__Vorbis__LibVorbis_get_vorbis_info, file);
        newXS("Ogg::Vorbis::LibVorbis::get_vorbis_comment", XS_Ogg__Vorbis__LibVorbis_get_vorbis_comment, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

