/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2206 from the
 * contents of LibVorbis.xs. Do not edit this file, edit LibVorbis.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "LibVorbis.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include <stdio.h>
#include <ogg/ogg.h>
#include <vorbis/codec.h>
#include <vorbis/vorbisenc.h>
#include <vorbis/vorbisfile.h>

#include "const-c.inc"

typedef PerlIO *        OutputStream;
typedef PerlIO *        InputStream;

#line 28 "LibVorbis.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 80 "LibVorbis.c"

/* INCLUDE:  Including 'const-xs.inc' from 'LibVorbis.xs' */


XS(XS_Ogg__Vorbis__LibVorbis_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_constant)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "./const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	IV		iv;
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 109 "LibVorbis.c"
	SV *	sv = ST(0);
	const char *	s = SvPV(sv, len);
#line 18 "./const-xs.inc"
        /* Change this to constant(aTHX_ s, len, &iv, &nv);
           if you need to return both NVs and IVs */
	type = constant(aTHX_ s, len, &iv);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid Ogg::Vorbis::LibVorbis macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined Ogg::Vorbis::LibVorbis macro %s, used",
				   s));
          PUSHs(sv);
          break;
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break;
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing Ogg::Vorbis::LibVorbis macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 186 "LibVorbis.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'LibVorbis.xs' from 'const-xs.inc' */


XS(XS_Ogg__Vorbis__LibVorbis_make_oggvorbis_file); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_make_oggvorbis_file)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 44 "LibVorbis.xs"
    OggVorbis_File *memory;
#line 209 "LibVorbis.c"
	OggVorbis_File *	RETVAL;
	dXSTARG;
#line 46 "LibVorbis.xs"
    New(0, memory, 1, OggVorbis_File);
    RETVAL = memory;
#line 215 "LibVorbis.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_make_vorbis_info); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_make_vorbis_info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 67 "LibVorbis.xs"
    vorbis_info *	memory;
#line 235 "LibVorbis.c"
	vorbis_info *	RETVAL;
	dXSTARG;
#line 69 "LibVorbis.xs"
    New(0, memory, 1, vorbis_info);
    RETVAL = memory;
#line 241 "LibVorbis.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_open); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_open)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "f, vf, initial, ibytes");
    {
	InputStream	f = IoIFP(sv_2io(ST(0)));
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(1)));
	char *	initial = (char *)SvPV_nolen(ST(2));
	int	ibytes = (int)SvIV(ST(3));
#line 113 "LibVorbis.xs"
    FILE *fp = PerlIO_findFILE(f);
#line 265 "LibVorbis.c"
	int	RETVAL;
	dXSTARG;
#line 115 "LibVorbis.xs"
    /* check whether it is a valid file handler */
    if (fp == (FILE*) 0 || fileno(fp) <= 0) {   
      Perl_croak(aTHX_ "Expected Open FILE HANDLER");
    }
    /* open the vorbis file */
    RETVAL = ov_open(fp, vf, initial, ibytes);
#line 275 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_clear); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_clear)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	RETVAL;
	dXSTARG;
#line 143 "LibVorbis.xs"
    RETVAL = ov_clear(vf);
#line 298 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_seekable); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_seekable)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	RETVAL;
	dXSTARG;
#line 167 "LibVorbis.xs"
    RETVAL = ov_seekable(vf);
#line 321 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_time_total); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_time_total)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, i");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	i = (int)SvIV(ST(1));
	double	RETVAL;
	dXSTARG;
#line 194 "LibVorbis.xs"
    RETVAL = ov_time_total(vf, i);
#line 345 "LibVorbis.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, s");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	double	s = (double)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 226 "LibVorbis.xs"
    RETVAL = ov_time_seek(vf, s);
#line 369 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_streams); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_streams)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	long	RETVAL;
	dXSTARG;
#line 250 "LibVorbis.xs"
    RETVAL = ov_streams(vf);
#line 392 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_info); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, link");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	link = (int)SvIV(ST(1));
	vorbis_info *	RETVAL;
	dXSTARG;
#line 276 "LibVorbis.xs"
    RETVAL = ov_info(vf, link);
#line 416 "LibVorbis.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ogg__Vorbis__LibVorbis); /* prototype to pass -Wmissing-prototypes */
XS(boot_Ogg__Vorbis__LibVorbis)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Ogg::Vorbis::LibVorbis::constant", XS_Ogg__Vorbis__LibVorbis_constant, file);
        newXS("Ogg::Vorbis::LibVorbis::make_oggvorbis_file", XS_Ogg__Vorbis__LibVorbis_make_oggvorbis_file, file);
        newXS("Ogg::Vorbis::LibVorbis::make_vorbis_info", XS_Ogg__Vorbis__LibVorbis_make_vorbis_info, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_open", XS_Ogg__Vorbis__LibVorbis_ov_open, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_clear", XS_Ogg__Vorbis__LibVorbis_ov_clear, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_seekable", XS_Ogg__Vorbis__LibVorbis_ov_seekable, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_time_total", XS_Ogg__Vorbis__LibVorbis_ov_time_total, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_time_seek", XS_Ogg__Vorbis__LibVorbis_ov_time_seek, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_streams", XS_Ogg__Vorbis__LibVorbis_ov_streams, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_info", XS_Ogg__Vorbis__LibVorbis_ov_info, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

