/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.2206 from the
 * contents of LibVorbis.xs. Do not edit this file, edit LibVorbis.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "LibVorbis.xs"
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <errno.h>
#include <stdlib.h>

#include <ogg/ogg.h>
#include <vorbis/codec.h>
#include <vorbis/vorbisenc.h>
#include <vorbis/vorbisfile.h>

#include "const-c.inc"

static size_t ovcb_read(void *ptr, size_t size, size_t nmemb, void *datasource);
static int    ovcb_seek(void *datasource, ogg_int64_t offset, int whence);
static int    ovcb_close(void *datasource);
static long   ovcb_tell(void *datasource);

/* http://www.xiph.org/ogg/vorbis/doc/vorbisfile/ov_callbacks.html */
ov_callbacks vorbis_callbacks = {
	ovcb_read,
	ovcb_seek,
	ovcb_close,
	ovcb_tell
};

/* Allow multiple instances of the decoder object. Stuff each filehandle into (void*)stream */
typedef struct {
	int is_streaming;
	int bytes_streamed;
	int last_bitstream;
	PerlIO *stream;

} ocvb_datasource;

typedef PerlIO *        OutputStream;
typedef PerlIO *        InputStream;

static int _arr_rows;
static int _arr_cols;

/* useful items from XMMS */
static size_t ovcb_read(void *ptr, size_t size, size_t nmemb, void *vdatasource) {

  size_t read_bytes = 0;
  ocvb_datasource *datasource = vdatasource;

  read_bytes = PerlIO_read(datasource->stream, ptr, size * nmemb);
  datasource->bytes_streamed += read_bytes;

  return read_bytes;
}

static int ovcb_seek(void *vdatasource, ogg_int64_t offset, int whence) {

  ocvb_datasource *datasource = vdatasource;

  if (datasource->is_streaming) {
    return -1;
  }

  /* For some reason PerlIO_seek fails miserably here. < 5.8.1 works */
  /* return PerlIO_seek(datasource->stream, offset, whence); */

  return fseek(PerlIO_findFILE(datasource->stream), offset, whence);
}

static int ovcb_close(void *vdatasource) {

  ocvb_datasource *datasource = vdatasource;

  return PerlIO_close(datasource->stream);
}

static long ovcb_tell(void *vdatasource) {

  ocvb_datasource *datasource = vdatasource;

  if (datasource->is_streaming) {
    return datasource->bytes_streamed;
  }

  return PerlIO_tell(datasource->stream);
}

static void * get_mortalspace ( size_t nbytes ) {
  SV * mortal;
  mortal = sv_2mortal( NEWSV(0, nbytes ) );
  return (void *) SvPVX( mortal );
}

/* Handler for unpacking (float **) */
float ** XS_unpack_floatPtrPtr(SV * arg ) { 
  AV * avref;
  AV * avref_2; 
  float ** array;
  SV ** data; 
  int len, len_2; 
  SV ** elem; 
  int i, j; 

  avref = (AV*)SvRV(arg); 
  len = av_len( avref ) + 1; 
  /* First allocate some memory for the pointers and a NULL for delimiter */ 
  array = (float **)get_mortalspace( (len+1) * sizeof( *array ));   
  /* Loop over each element copying pointers to the array */ 
  for (i=0; i<len; i++) { 
    /* now elem points to the 2nd array in 2D float array */
    elem = av_fetch( avref, i, 0); 
    /* get the pointer to inner array */
    avref_2 = (AV*)SvRV((SV *)*elem);
    /* get the length of the inner array */
    len_2 = av_len(avref_2) + 1;
    /* create mortal space for the 2D array (+1 for NULL delimiter) */
    array[i] = (float *)get_mortalspace( (len_2+1) * sizeof(float));
    for (j=0; j<len_2; j++) {
      /* get the element */   
      data = av_fetch(avref_2, j, 0);
      /* fill the ARRAY */
      array[i][j] = SvNV(*data); 
    }
  } 

  /* hard code the row and col length */
  _arr_rows = i;
  _arr_cols = j;		/* all arrays are of same size */

  return array; 
} 

/* Handler for packing (float **) */
void XS_pack_floatPtrPtr( SV * arg, float ** array) { 
  int i, j; 
  AV *avref, *avref_2; 
  /* create an array_ref */
  avref  = (AV*)sv_2mortal((SV*)newAV()); 
  for (i=0; i<_arr_rows; i++) { 
    /* ref to inner array */
    avref_2  = (AV*)sv_2mortal((SV*)newAV()); 
    /* populate inner array */
    for (j=0; j<_arr_cols; j++) {
      av_push(avref_2, newSVnv(array[i][j]));
    }
    /* create a reference to array (inner) */
    av_push(avref, newRV((SV*)avref_2));
  } 

  /* pack the data in 'arg' and put it back in 'arg' */
  SvSetSV( arg, newRV((SV*)avref)); 
} 



#line 170 "LibVorbis.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)	S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage		S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 222 "LibVorbis.c"

/* INCLUDE:  Including 'const-xs.inc' from 'LibVorbis.xs' */


XS(XS_Ogg__Vorbis__LibVorbis_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_constant)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "sv");
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 4 "./const-xs.inc"
#ifdef dXSTARG
	dXSTARG; /* Faster if we have it.  */
#else
	dTARGET;
#endif
	STRLEN		len;
        int		type;
	IV		iv;
	/* NV		nv;	Uncomment this if you need to return NVs */
	/* const char	*pv;	Uncomment this if you need to return PVs */
#line 251 "LibVorbis.c"
	SV *	sv = ST(0);
	const char *	s = SvPV(sv, len);
#line 18 "./const-xs.inc"
        /* Change this to constant(aTHX_ s, len, &iv, &nv);
           if you need to return both NVs and IVs */
	type = constant(aTHX_ s, len, &iv);
      /* Return 1 or 2 items. First is error message, or undef if no error.
           Second, if present, is found value */
        switch (type) {
        case PERL_constant_NOTFOUND:
          sv =
	    sv_2mortal(newSVpvf("%s is not a valid Ogg::Vorbis::LibVorbis macro", s));
          PUSHs(sv);
          break;
        case PERL_constant_NOTDEF:
          sv = sv_2mortal(newSVpvf(
	    "Your vendor has not defined Ogg::Vorbis::LibVorbis macro %s, used",
				   s));
          PUSHs(sv);
          break;
        case PERL_constant_ISIV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHi(iv);
          break;
	/* Uncomment this if you need to return NOs
        case PERL_constant_ISNO:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_no);
          break; */
	/* Uncomment this if you need to return NVs
        case PERL_constant_ISNV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHn(nv);
          break; */
	/* Uncomment this if you need to return PVs
        case PERL_constant_ISPV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, strlen(pv));
          break; */
	/* Uncomment this if you need to return PVNs
        case PERL_constant_ISPVN:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHp(pv, iv);
          break; */
	/* Uncomment this if you need to return SVs
        case PERL_constant_ISSV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(sv);
          break; */
	/* Uncomment this if you need to return UNDEFs
        case PERL_constant_ISUNDEF:
          break; */
	/* Uncomment this if you need to return UVs
        case PERL_constant_ISUV:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHu((UV)iv);
          break; */
	/* Uncomment this if you need to return YESs
        case PERL_constant_ISYES:
          EXTEND(SP, 1);
          PUSHs(&PL_sv_undef);
          PUSHs(&PL_sv_yes);
          break; */
        default:
          sv = sv_2mortal(newSVpvf(
	    "Unexpected return type %d while processing Ogg::Vorbis::LibVorbis macro %s, used",
               type, s));
          PUSHs(sv);
        }
#line 328 "LibVorbis.c"
	PUTBACK;
	return;
    }
}


/* INCLUDE: Returning to 'LibVorbis.xs' from 'const-xs.inc' */


XS(XS_Ogg__Vorbis__LibVorbis_make_oggvorbis_file); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_make_oggvorbis_file)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 186 "LibVorbis.xs"
    OggVorbis_File *memory;
#line 351 "LibVorbis.c"
	OggVorbis_File *	RETVAL;
	dXSTARG;
#line 188 "LibVorbis.xs"
    New(0, memory, 1, OggVorbis_File);
    RETVAL = memory;
#line 357 "LibVorbis.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_make_vorbis_info); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_make_vorbis_info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 209 "LibVorbis.xs"
    vorbis_info *	memory;
#line 377 "LibVorbis.c"
	vorbis_info *	RETVAL;
	dXSTARG;
#line 211 "LibVorbis.xs"
    New(0, memory, 1, vorbis_info);
    RETVAL = memory;
#line 383 "LibVorbis.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_make_vorbis_comment); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_make_vorbis_comment)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 232 "LibVorbis.xs"
    vorbis_comment *	memory;
#line 403 "LibVorbis.c"
	vorbis_comment *	RETVAL;
	dXSTARG;
#line 234 "LibVorbis.xs"
    New(0, memory, 1, vorbis_comment);
    RETVAL = memory;
#line 409 "LibVorbis.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_make_vorbis_block); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_make_vorbis_block)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 254 "LibVorbis.xs"
    vorbis_block *	memory;
#line 429 "LibVorbis.c"
	vorbis_block *	RETVAL;
	dXSTARG;
#line 256 "LibVorbis.xs"
    New(0, memory, 1, vorbis_block);
    RETVAL = memory;
#line 435 "LibVorbis.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_make_vorbis_dsp_state); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_make_vorbis_dsp_state)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 277 "LibVorbis.xs"
    vorbis_dsp_state *	memory;
#line 455 "LibVorbis.c"
	vorbis_dsp_state *	RETVAL;
	dXSTARG;
#line 279 "LibVorbis.xs"
    New(0, memory, 1, vorbis_dsp_state);
    RETVAL = memory;
#line 461 "LibVorbis.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_open); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_open)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "f, vf, initial, ibytes");
    {
	InputStream	f = IoIFP(sv_2io(ST(0)));
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(1)));
	char *	initial = (char *)SvPV_nolen(ST(2));
	int	ibytes = (int)SvIV(ST(3));
#line 322 "LibVorbis.xs"
    FILE *fp = PerlIO_findFILE(f);
#line 485 "LibVorbis.c"
	int	RETVAL;
	dXSTARG;
#line 324 "LibVorbis.xs"
    /* check whether it is a valid file handler */
    if (fp == (FILE*) 0 || fileno(fp) <= 0) {   
      Perl_croak(aTHX_ "Expected Open FILE HANDLER");
    }
    /* open the vorbis file */
    RETVAL = ov_open(fp, vf, initial, ibytes);
#line 495 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_fopen); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_fopen)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "path, vf");
    {
	char *	path = (char *)SvPV_nolen(ST(0));
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(1)));
	int	RETVAL;
	dXSTARG;
#line 359 "LibVorbis.xs"
    RETVAL = ov_fopen(path, vf);
#line 519 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_open_callbacks); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_open_callbacks)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "path, vf, initial, ibytes");
    {
	SV *	path = ST(0);
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(1)));
	char *	initial = (char *)SvPV_nolen(ST(2));
	int	ibytes = (int)SvIV(ST(3));
#line 400 "LibVorbis.xs"
    FILE *fp;
#line 543 "LibVorbis.c"
	int	RETVAL;
	dXSTARG;
#line 402 "LibVorbis.xs"
    int ret = 10;

    /* our stash for streams */
    ocvb_datasource *datasource = (ocvb_datasource *) safemalloc(sizeof(ocvb_datasource));
    memset(datasource, 0, sizeof(ocvb_datasource));

    /* check and see if a pathname was passed in, otherwise it might be a
     * IO::Socket subclass, or even a *FH Glob */
    if (SvOK(path) && (SvTYPE(SvRV(path)) != SVt_PVGV)) {

      if ((datasource->stream = PerlIO_open((char*)SvPV_nolen(path), "r")) == NULL) {
        safefree(vf);
        fprintf(stderr, "failed on open: [%d] - [%s]\n", errno, strerror(errno));
        XSRETURN_UNDEF;
      }

      datasource->is_streaming = 0;

    } else if (SvOK(path)) {

      /* Did we get a Glob, or a IO::Socket subclass? */		
      if (sv_isobject(path) && sv_derived_from(path, "IO::Socket")) {
        datasource->is_streaming = 1;
      } else {

        datasource->is_streaming = 0;
      }

      /* dereference and get the SV* that contains the Magic & FH,
       * then pull the fd from the PerlIO object */
      datasource->stream = IoIFP(GvIOp(SvRV(path)));

    } else {

      fp = PerlIO_findFILE((PerlIO *)IoIFP(sv_2io(path)));
      /* check whether it is a valid file handler */
      if (fp == (FILE*) 0 || fileno(fp) <= 0) {   
         XSRETURN_UNDEF;
      }
      datasource->stream = (PerlIO *)IoIFP(sv_2io(path));
    }

    if ((ret = ov_open_callbacks((void*)datasource, vf, NULL, 0, vorbis_callbacks)) < 0) {
      warn("Failed on registering callbacks: [%d]\n", ret);
      printf("failed on open: [%d] - [%s]\n", errno, strerror(errno));
      ov_clear(vf);

      XSRETURN_UNDEF;
    }

    datasource->bytes_streamed = 0;
    datasource->last_bitstream = -1;

    RETVAL = ret;

#line 602 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_test); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_test)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "f, vf, initial, ibytes");
    {
	InputStream	f = IoIFP(sv_2io(ST(0)));
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(1)));
	char *	initial = (char *)SvPV_nolen(ST(2));
	long	ibytes = (long)SvIV(ST(3));
#line 491 "LibVorbis.xs"
    FILE *fp = PerlIO_findFILE(f);
#line 626 "LibVorbis.c"
	int	RETVAL;
	dXSTARG;
#line 493 "LibVorbis.xs"
    if (fp == (FILE*) 0 || fileno(fp) <= 0) {   
       XSRETURN_UNDEF;
    }    
    /* open the vorbis file */
    RETVAL = ov_test(fp, vf, initial, ibytes);
#line 635 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_test_open); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_test_open)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	RETVAL;
	dXSTARG;
#line 526 "LibVorbis.xs"
    RETVAL = ov_test_open(vf);
#line 658 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_test_callbacks); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_test_callbacks)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "path, vf, initial, ibytes");
    {
	SV *	path = ST(0);
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(1)));
	char *	initial = (char *)SvPV_nolen(ST(2));
	int	ibytes = (int)SvIV(ST(3));
#line 567 "LibVorbis.xs"
    FILE *fp;
#line 682 "LibVorbis.c"
	int	RETVAL;
	dXSTARG;
#line 569 "LibVorbis.xs"
    int ret = 10;

    /* our stash for streams */
    ocvb_datasource *datasource = (ocvb_datasource *) safemalloc(sizeof(ocvb_datasource));
    memset(datasource, 0, sizeof(ocvb_datasource));

    /* check and see if a pathname was passed in, otherwise it might be a
     * IO::Socket subclass, or even a *FH Glob */
    if (SvOK(path) && (SvTYPE(SvRV(path)) != SVt_PVGV)) {

      if ((datasource->stream = PerlIO_open((char*)SvPV_nolen(path), "r")) == NULL) {
        safefree(vf);
        printf("failed on open: [%d] - [%s]\n", errno, strerror(errno));
        XSRETURN_UNDEF;
      }

      datasource->is_streaming = 0;

    } else if (SvOK(path)) {

      /* Did we get a Glob, or a IO::Socket subclass? */		
      if (sv_isobject(path) && sv_derived_from(path, "IO::Socket")) {
        datasource->is_streaming = 1;
      } else {

        datasource->is_streaming = 0;
      }

      /* dereference and get the SV* that contains the Magic & FH,
       * then pull the fd from the PerlIO object */
      datasource->stream = IoIFP(GvIOp(SvRV(path)));

    } else {

      fp = PerlIO_findFILE((PerlIO *)IoIFP(sv_2io(path)));
      /* check whether it is a valid file handler */
      if (fp == (FILE*) 0 || fileno(fp) <= 0) {   
         XSRETURN_UNDEF;
      }
      datasource->stream = (PerlIO *)IoIFP(sv_2io(path));
    }

    if ((ret = ov_test_callbacks((void*)datasource, vf, NULL, 0, vorbis_callbacks)) < 0) {
      warn("Failed on registering callbacks: [%d]\n", ret);
      printf("failed on open: [%d] - [%s]\n", errno, strerror(errno));
      ov_clear(vf);

      XSRETURN_UNDEF;
    }

    datasource->bytes_streamed = 0;
    datasource->last_bitstream = -1;

    RETVAL = ret;

#line 741 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_clear); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_clear)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	RETVAL;
	dXSTARG;
#line 646 "LibVorbis.xs"
    RETVAL = ov_clear(vf);
#line 764 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_seekable); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_seekable)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	RETVAL;
	dXSTARG;
#line 669 "LibVorbis.xs"
    RETVAL = ov_seekable(vf);
#line 787 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_time_total); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_time_total)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, i");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	i = (int)SvIV(ST(1));
	double	RETVAL;
	dXSTARG;
#line 695 "LibVorbis.xs"
    RETVAL = ov_time_total(vf, i);
#line 811 "LibVorbis.c"
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, s");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	double	s = (double)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 726 "LibVorbis.xs"
    RETVAL = ov_time_seek(vf, s);
#line 835 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_seek); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_seek)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, s");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	long	s = (long)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 757 "LibVorbis.xs"
    RETVAL = ov_raw_seek(vf, s);
#line 859 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, s");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	ogg_int64_t	s = (ogg_int64_t)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 788 "LibVorbis.xs"
    RETVAL = ov_pcm_seek(vf, s);
#line 883 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_page); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_page)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, pos");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	ogg_int64_t	pos = (ogg_int64_t)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 819 "LibVorbis.xs"
    RETVAL = ov_pcm_seek_page(vf, pos);
#line 907 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek_page); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek_page)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, pos");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	double	pos = (double)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 850 "LibVorbis.xs"
    RETVAL = ov_time_seek_page(vf, pos);
#line 931 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_seek_lap); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_seek_lap)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, pos");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	ogg_int64_t	pos = (ogg_int64_t)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 882 "LibVorbis.xs"
    RETVAL = ov_raw_seek_lap(vf, pos);
#line 955 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_lap); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_lap)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, pos");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	long	pos = (long)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 914 "LibVorbis.xs"
    RETVAL = ov_pcm_seek_lap(vf, pos);
#line 979 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek_lap); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek_lap)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, pos");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	double	pos = (double)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 946 "LibVorbis.xs"
    RETVAL = ov_time_seek_lap(vf, pos);
#line 1003 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek_page_lap); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_time_seek_page_lap)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, pos");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	double	pos = (double)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 978 "LibVorbis.xs"
    RETVAL = ov_time_seek_page_lap(vf, pos);
#line 1027 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_page_lap); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_page_lap)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, pos");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	ogg_int64_t	pos = (ogg_int64_t)SvNV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 1010 "LibVorbis.xs"
    RETVAL = ov_pcm_seek_page_lap(vf, pos);
#line 1051 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_streams); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_streams)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	long	RETVAL;
	dXSTARG;
#line 1033 "LibVorbis.xs"
    RETVAL = ov_streams(vf);
#line 1074 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_info); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, link");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	link = (int)SvIV(ST(1));
	vorbis_info *	RETVAL;
	dXSTARG;
#line 1058 "LibVorbis.xs"
    RETVAL = ov_info(vf, link);
#line 1098 "LibVorbis.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_bitrate); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_bitrate)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, i");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	i = (int)SvIV(ST(1));
	long	RETVAL;
	dXSTARG;
#line 1083 "LibVorbis.xs"
    RETVAL = ov_bitrate(vf, i);
#line 1122 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_bitrate_instant); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_bitrate_instant)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	long	RETVAL;
	dXSTARG;
#line 1107 "LibVorbis.xs"
    RETVAL = ov_bitrate_instant(vf);
#line 1145 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_serialnumber); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_serialnumber)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, i");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	i = (int)SvIV(ST(1));
	long	RETVAL;
	dXSTARG;
#line 1132 "LibVorbis.xs"
    RETVAL = ov_serialnumber(vf, i);
#line 1169 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_total); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_total)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, i");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	i = (int)SvIV(ST(1));
	long	RETVAL;
	dXSTARG;
#line 1158 "LibVorbis.xs"
    RETVAL = ov_raw_total(vf, i);
#line 1193 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_total); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_total)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, i");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	i = (int)SvIV(ST(1));
	ogg_int64_t	RETVAL;
	dXSTARG;
#line 1183 "LibVorbis.xs"
    RETVAL = ov_pcm_total(vf, i);
#line 1217 "LibVorbis.c"
	XSprePUSH; PUSHn((NV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_tell); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_raw_tell)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	ogg_int64_t	RETVAL;
	dXSTARG;
#line 1206 "LibVorbis.xs"
    RETVAL = ov_raw_tell(vf);
#line 1240 "LibVorbis.c"
	XSprePUSH; PUSHn((NV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_tell); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_pcm_tell)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	ogg_int64_t	RETVAL;
	dXSTARG;
#line 1229 "LibVorbis.xs"
    RETVAL = ov_pcm_tell(vf);
#line 1263 "LibVorbis.c"
	XSprePUSH; PUSHn((NV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_time_tell); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_time_tell)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vf");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	ogg_int64_t	RETVAL;
	dXSTARG;
#line 1252 "LibVorbis.xs"
    RETVAL = ov_time_tell(vf);
#line 1286 "LibVorbis.c"
	XSprePUSH; PUSHn((NV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_comment); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_comment)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vf, link");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	int	link = (int)SvIV(ST(1));
	vorbis_comment *	RETVAL;
	dXSTARG;
#line 1277 "LibVorbis.xs"
    RETVAL = ov_comment(vf, link);
#line 1310 "LibVorbis.c"
	XSprePUSH; PUSHi(PTR2IV(RETVAL));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_ov_read); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_ov_read)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 7)
       croak_xs_usage(cv,  "vf, buffer, length, big, word, sgned, bit");
    {
	OggVorbis_File *	vf = INT2PTR(OggVorbis_File *,SvIV(ST(0)));
	char *	buffer;
	int	length = (int)SvIV(ST(2));
	int	big = (int)SvIV(ST(3));
	int	word = (int)SvIV(ST(4));
	int	sgned = (int)SvIV(ST(5));
	int	bit;
	long	RETVAL;
	dXSTARG;
#line 1315 "LibVorbis.xs"
    New(0, buffer, length, char);
    RETVAL = ov_read(vf, buffer, length, big, word, sgned, &bit);
    // if you dig deep in the XS, you will see char * is T_PV which is 
    // sv_setpv for OUTPUT and SvPV_nolen for input
    sv_setpvn((SV*)ST(1), buffer, RETVAL); 
    SvSETMAGIC(ST(1));
    XSprePUSH; 
#line 1345 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
#line 1325 "LibVorbis.xs"
    Safefree(buffer);
#line 1349 "LibVorbis.c"
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_vorbis_info_init); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_vorbis_info_init)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vi");
    {
	vorbis_info *	vi = INT2PTR(vorbis_info *,SvIV(ST(0)));
#line 1361 "LibVorbis.xs"
    vorbis_info_init(vi);
#line 1369 "LibVorbis.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Ogg__Vorbis__LibVorbis_vorbis_encode_init_vbr); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_vorbis_encode_init_vbr)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "vi, channels, rate, base_quality");
    {
	vorbis_info *	vi = INT2PTR(vorbis_info *,SvIV(ST(0)));
	long	channels = (long)SvIV(ST(1));
	long	rate = (long)SvIV(ST(2));
	float	base_quality = (float)SvNV(ST(3));
	int	RETVAL;
	dXSTARG;
#line 1391 "LibVorbis.xs"
    RETVAL = vorbis_encode_init_vbr(vi, channels, rate, base_quality);
#line 1394 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_init); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_init)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "v, vi");
    {
	vorbis_dsp_state *	v = INT2PTR(vorbis_dsp_state *,SvIV(ST(0)));
	vorbis_info *	vi = INT2PTR(vorbis_info *,SvIV(ST(1)));
	int	RETVAL;
	dXSTARG;
#line 1416 "LibVorbis.xs"
    RETVAL = vorbis_analysis_init(v, vi);
#line 1418 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_vorbis_block_init); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_vorbis_block_init)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "v, vb");
    {
	vorbis_dsp_state *	v = INT2PTR(vorbis_dsp_state *,SvIV(ST(0)));
	vorbis_block *	vb = INT2PTR(vorbis_block *,SvIV(ST(1)));
	int	RETVAL;
	dXSTARG;
#line 1440 "LibVorbis.xs"
    RETVAL = vorbis_block_init(v, vb);
#line 1442 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_vorbis_encode_setup_init); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_vorbis_encode_setup_init)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vi");
    {
	vorbis_info *	vi = INT2PTR(vorbis_info *,SvIV(ST(0)));
	int	RETVAL;
	dXSTARG;
#line 1467 "LibVorbis.xs"
    RETVAL = vorbis_encode_setup_init(vi);
#line 1465 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_vorbis_comment_init); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_vorbis_comment_init)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vc");
    {
	vorbis_comment *	vc = INT2PTR(vorbis_comment *,SvIV(ST(0)));
#line 1488 "LibVorbis.xs"
    vorbis_comment_init(vc);
#line 1486 "LibVorbis.c"
    }
    XSRETURN_EMPTY;
}


XS(XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_headerout); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_headerout)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 5)
       croak_xs_usage(cv,  "v, vc, op, op_comm, op_code");
    {
	vorbis_dsp_state *	v = INT2PTR(vorbis_dsp_state *,SvIV(ST(0)));
	vorbis_comment *	vc = INT2PTR(vorbis_comment *,SvIV(ST(1)));
	ogg_packet *	op = INT2PTR(ogg_packet *,SvIV(ST(2)));
	ogg_packet *	op_comm = INT2PTR(ogg_packet *,SvIV(ST(3)));
	ogg_packet *	op_code = INT2PTR(ogg_packet *,SvIV(ST(4)));
	int	RETVAL;
	dXSTARG;
#line 1519 "LibVorbis.xs"
    RETVAL = vorbis_analysis_headerout(v, vc, op, op_comm, op_code);
#line 1512 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_buffer); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_buffer)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "v, vals");
    {
	vorbis_dsp_state *	v = INT2PTR(vorbis_dsp_state *,SvIV(ST(0)));
	int	vals = (int)SvIV(ST(1));
	float **	RETVAL;
#line 1543 "LibVorbis.xs"
    RETVAL = vorbis_analysis_buffer(v, vals);
#line 1535 "LibVorbis.c"
	ST(0) = sv_newmortal();
	XS_pack_floatPtrPtr(ST(0), RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_wrote); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_wrote)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "v, val");
    {
	vorbis_dsp_state *	v = INT2PTR(vorbis_dsp_state *,SvIV(ST(0)));
	int	val = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 1571 "LibVorbis.xs"
    RETVAL = vorbis_analysis_wrote(v, val);
#line 1560 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_blockout); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_blockout)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "v, vb");
    {
	vorbis_dsp_state *	v = INT2PTR(vorbis_dsp_state *,SvIV(ST(0)));
	vorbis_block *	vb = INT2PTR(vorbis_block *,SvIV(ST(1)));
	int	RETVAL;
	dXSTARG;
#line 1600 "LibVorbis.xs"
    RETVAL = vorbis_analysis_blockout(v, vb);
#line 1584 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_vorbis_analysis); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_vorbis_analysis)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 2)
       croak_xs_usage(cv,  "vb, op");
    {
	vorbis_block *	vb = INT2PTR(vorbis_block *,SvIV(ST(0)));
	ogg_packet *	op = INT2PTR(ogg_packet *,SvIV(ST(1)));
	int	RETVAL;
	dXSTARG;
#line 1628 "LibVorbis.xs"
    RETVAL = vorbis_analysis(vb, op);
#line 1608 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_get_vorbis_info); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_get_vorbis_info)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vi");
    {
	vorbis_info *	vi = INT2PTR(vorbis_info *,SvIV(ST(0)));
#line 1657 "LibVorbis.xs"
    HV * hash;
#line 1629 "LibVorbis.c"
	HV *	RETVAL;
#line 1659 "LibVorbis.xs"
    hash = newHV();

    sv_2mortal((SV *)hash);	/* convert the HASH to a mortal */
    hv_store(hash, "version", strlen("version"), newSVnv(vi->version), 0); 
    hv_store(hash, "channels", strlen("channels"), newSViv(vi->channels), 0); 
    hv_store(hash, "rate", strlen("rate"), newSVnv(vi->rate), 0);
    hv_store(hash, "bitrate_upper", strlen("bitrate_upper"), newSVnv(vi->bitrate_upper), 0);
    hv_store(hash, "bitrate_nominal", strlen("bitrate_nominal"), newSVnv(vi->bitrate_nominal), 0);
    hv_store(hash, "bitrate_lower", strlen("bitrate_lower"), newSVnv(vi->bitrate_lower), 0);
    hv_store(hash, "bitrate_window", strlen("bitrate_window"), newSVnv(vi->bitrate_window), 0);
    hv_store(hash, "codec_setup", strlen("codec_setup"), newSViv(PTR2IV(vi->codec_setup)), 0);

    RETVAL = hash;
#line 1645 "LibVorbis.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_get_vorbis_comment); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_get_vorbis_comment)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       croak_xs_usage(cv,  "vc");
    {
	vorbis_comment *	vc = INT2PTR(vorbis_comment *,SvIV(ST(0)));
#line 1693 "LibVorbis.xs"
    HV * hash;
    AV * uc;			/* user comments */
    AV * cl;			/* comment lenth */
    int i = 0;
#line 1670 "LibVorbis.c"
	HV *	RETVAL;
#line 1698 "LibVorbis.xs"
    hash = newHV();
    sv_2mortal((SV *)hash);

    uc = newAV();
    cl = newAV();
    /* get the user comments and put in hash */
    for (i=0; i<vc->comments; i++) {
      av_push(uc, newSVpv(vc->user_comments[i], 0));
      av_push(cl, newSViv(vc->comment_lengths[i]));
    } 

    /* store the user comments */
    hv_store(hash, "user_comments", strlen("user_comments"), newRV_noinc((SV *)uc), 0);      
    /* store the comment length */
    hv_store(hash, "comment_lenghts", strlen("comment_lenghts"), newRV_noinc((SV *)cl), 0);      
    /* get the vendor */
    hv_store(hash, "vendor", strlen("vendor"), newSVpv(vc->vendor, 0), 0);      
    /* number of comments */
    hv_store(hash, "comments", strlen("comments"), newSViv(vc->comments), 0);      

    RETVAL = hash;

#line 1695 "LibVorbis.c"
	ST(0) = newRV((SV*)RETVAL);
	sv_2mortal(ST(0));
    }
    XSRETURN(1);
}


XS(XS_Ogg__Vorbis__LibVorbis_vorbis_encode_wav_frames); /* prototype to pass -Wmissing-prototypes */
XS(XS_Ogg__Vorbis__LibVorbis_vorbis_encode_wav_frames)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 4)
       croak_xs_usage(cv,  "v, vals, channels, buffer");
    {
	vorbis_dsp_state *	v = INT2PTR(vorbis_dsp_state *,SvIV(ST(0)));
	int	vals = (int)SvIV(ST(1));
	int	channels = (int)SvIV(ST(2));
	char *	buffer = (char *)SvPV_nolen(ST(3));
#line 1747 "LibVorbis.xs"
    float ** vorbis_buffer;
    int i, j;
    int count = 0;
#line 1722 "LibVorbis.c"
	int	RETVAL;
	dXSTARG;
#line 1751 "LibVorbis.xs"
   vorbis_buffer=vorbis_analysis_buffer(v, vals);

   if (vorbis_buffer == NULL)
     fprintf(stderr, "vorbis_analysis_buffer returned NULL, float ** was expected (might crap out soon)\n");

   /* uninterleave samples */
   for(i=0; i<vals; i++){
     for(j=0; j<channels; j++){
       vorbis_buffer[j][i]=((buffer[count+1]<<8)|
			   (0x00ff&(int)buffer[count]))/32768.f;
       count+=2;
     }
   }

   RETVAL = vorbis_analysis_wrote(v, channels);
#line 1741 "LibVorbis.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Ogg__Vorbis__LibVorbis); /* prototype to pass -Wmissing-prototypes */
XS(boot_Ogg__Vorbis__LibVorbis)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("Ogg::Vorbis::LibVorbis::constant", XS_Ogg__Vorbis__LibVorbis_constant, file);
        newXS("Ogg::Vorbis::LibVorbis::make_oggvorbis_file", XS_Ogg__Vorbis__LibVorbis_make_oggvorbis_file, file);
        newXS("Ogg::Vorbis::LibVorbis::make_vorbis_info", XS_Ogg__Vorbis__LibVorbis_make_vorbis_info, file);
        newXS("Ogg::Vorbis::LibVorbis::make_vorbis_comment", XS_Ogg__Vorbis__LibVorbis_make_vorbis_comment, file);
        newXS("Ogg::Vorbis::LibVorbis::make_vorbis_block", XS_Ogg__Vorbis__LibVorbis_make_vorbis_block, file);
        newXS("Ogg::Vorbis::LibVorbis::make_vorbis_dsp_state", XS_Ogg__Vorbis__LibVorbis_make_vorbis_dsp_state, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_open", XS_Ogg__Vorbis__LibVorbis_ov_open, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_fopen", XS_Ogg__Vorbis__LibVorbis_ov_fopen, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_open_callbacks", XS_Ogg__Vorbis__LibVorbis_ov_open_callbacks, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_test", XS_Ogg__Vorbis__LibVorbis_ov_test, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_test_open", XS_Ogg__Vorbis__LibVorbis_ov_test_open, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_test_callbacks", XS_Ogg__Vorbis__LibVorbis_ov_test_callbacks, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_clear", XS_Ogg__Vorbis__LibVorbis_ov_clear, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_seekable", XS_Ogg__Vorbis__LibVorbis_ov_seekable, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_time_total", XS_Ogg__Vorbis__LibVorbis_ov_time_total, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_time_seek", XS_Ogg__Vorbis__LibVorbis_ov_time_seek, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_raw_seek", XS_Ogg__Vorbis__LibVorbis_ov_raw_seek, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_pcm_seek", XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_pcm_seek_page", XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_page, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_time_seek_page", XS_Ogg__Vorbis__LibVorbis_ov_time_seek_page, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_raw_seek_lap", XS_Ogg__Vorbis__LibVorbis_ov_raw_seek_lap, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_pcm_seek_lap", XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_lap, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_time_seek_lap", XS_Ogg__Vorbis__LibVorbis_ov_time_seek_lap, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_time_seek_page_lap", XS_Ogg__Vorbis__LibVorbis_ov_time_seek_page_lap, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_pcm_seek_page_lap", XS_Ogg__Vorbis__LibVorbis_ov_pcm_seek_page_lap, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_streams", XS_Ogg__Vorbis__LibVorbis_ov_streams, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_info", XS_Ogg__Vorbis__LibVorbis_ov_info, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_bitrate", XS_Ogg__Vorbis__LibVorbis_ov_bitrate, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_bitrate_instant", XS_Ogg__Vorbis__LibVorbis_ov_bitrate_instant, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_serialnumber", XS_Ogg__Vorbis__LibVorbis_ov_serialnumber, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_raw_total", XS_Ogg__Vorbis__LibVorbis_ov_raw_total, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_pcm_total", XS_Ogg__Vorbis__LibVorbis_ov_pcm_total, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_raw_tell", XS_Ogg__Vorbis__LibVorbis_ov_raw_tell, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_pcm_tell", XS_Ogg__Vorbis__LibVorbis_ov_pcm_tell, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_time_tell", XS_Ogg__Vorbis__LibVorbis_ov_time_tell, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_comment", XS_Ogg__Vorbis__LibVorbis_ov_comment, file);
        newXS("Ogg::Vorbis::LibVorbis::ov_read", XS_Ogg__Vorbis__LibVorbis_ov_read, file);
        newXS("Ogg::Vorbis::LibVorbis::vorbis_info_init", XS_Ogg__Vorbis__LibVorbis_vorbis_info_init, file);
        newXS("Ogg::Vorbis::LibVorbis::vorbis_encode_init_vbr", XS_Ogg__Vorbis__LibVorbis_vorbis_encode_init_vbr, file);
        newXS("Ogg::Vorbis::LibVorbis::vorbis_analysis_init", XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_init, file);
        newXS("Ogg::Vorbis::LibVorbis::vorbis_block_init", XS_Ogg__Vorbis__LibVorbis_vorbis_block_init, file);
        newXS("Ogg::Vorbis::LibVorbis::vorbis_encode_setup_init", XS_Ogg__Vorbis__LibVorbis_vorbis_encode_setup_init, file);
        newXS("Ogg::Vorbis::LibVorbis::vorbis_comment_init", XS_Ogg__Vorbis__LibVorbis_vorbis_comment_init, file);
        newXS("Ogg::Vorbis::LibVorbis::vorbis_analysis_headerout", XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_headerout, file);
        newXS("Ogg::Vorbis::LibVorbis::vorbis_analysis_buffer", XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_buffer, file);
        newXS("Ogg::Vorbis::LibVorbis::vorbis_analysis_wrote", XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_wrote, file);
        newXS("Ogg::Vorbis::LibVorbis::vorbis_analysis_blockout", XS_Ogg__Vorbis__LibVorbis_vorbis_analysis_blockout, file);
        newXS("Ogg::Vorbis::LibVorbis::vorbis_analysis", XS_Ogg__Vorbis__LibVorbis_vorbis_analysis, file);
        newXS("Ogg::Vorbis::LibVorbis::get_vorbis_info", XS_Ogg__Vorbis__LibVorbis_get_vorbis_info, file);
        newXS("Ogg::Vorbis::LibVorbis::get_vorbis_comment", XS_Ogg__Vorbis__LibVorbis_get_vorbis_comment, file);
        newXS("Ogg::Vorbis::LibVorbis::vorbis_encode_wav_frames", XS_Ogg__Vorbis__LibVorbis_vorbis_encode_wav_frames, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

